# Generated by Django 5.0 on 2024-01-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerequest',
            old_name='model_version',
            new_name='model_name',
        ),
    ]
