# Generated by Django 5.0 on 2024-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0002_rename_model_version_imagerequest_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('month_requests', models.IntegerField(default=0)),
            ],
        ),
    ]
