# Generated by Django 4.2.7 on 2023-12-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0003_imagerequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
