# Generated by Django 4.2.7 on 2023-12-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0004_portstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField(unique=True)),
                ('queue_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PortStatus',
        ),
    ]
