# Generated by Django 4.2.7 on 2023-12-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0005_portqueue_delete_portstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, blank=True),
        ),
    ]
