# Generated by Django 4.2.7 on 2023-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0007_alter_imagerequest_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
