# Generated by Django 4.2.7 on 2023-12-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0009_imagerequest_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='None', max_length=20),
        ),
    ]
