# Generated by Django 4.2.7 on 2023-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0010_alter_imagerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('ready', 'Ready'), ('failed', 'Failed')], max_length=20),
        ),
    ]
