# Generated by Django 4.2.7 on 2023-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0011_alter_imagerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portqueue',
            name='queue_count',
        ),
        migrations.AddField(
            model_name='imagerequest',
            name='erorrs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portqueue',
            name='status_is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
