# Generated by Django 4.2.7 on 2023-12-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0015_remove_imagerequest_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='denoising_strength',
            field=models.FloatField(default=0.5),
        ),
    ]
