# Generated by Django 4.2.7 on 2023-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0016_alter_imagerequest_denoising_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='negative_prompt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagerequest',
            name='path_to_mask',
            field=models.TextField(default=''),
        ),
    ]
