# Generated by Django 4.2.7 on 2023-12-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0017_imagerequest_negative_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='negative_prompt',
            field=models.TextField(default=''),
        ),
    ]
