# Generated by Django 4.2.7 on 2023-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0019_imagerequest_inpainting_mask_invert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='inpainting_mask_invert',
            field=models.IntegerField(default=0),
        ),
    ]
