# Generated by Django 5.0 on 2023-12-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_img', '0020_alter_imagerequest_inpainting_mask_invert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortQueue',
            new_name='InterfaceQueue',
        ),
        migrations.RenameField(
            model_name='interfacequeue',
            old_name='port_number',
            new_name='interface',
        ),
    ]
